server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html/web;
    index kw.html index.html;

    location / {
        try_files $uri $uri/ /kw.html;
    }

    location /kw/ {
        alias /usr/share/nginx/html/kw/;
        try_files $uri $uri/ =404;
    }
}
