server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html/kw;
    index index.html;

    types {
        application/javascript js mjs;
        application/wasm wasm;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
